name: build-go-binary

on:
  release:
    types: [created] # 表示在创建新的 Release 时触发
  # push:
  # workflow_dispatch:

jobs:
  build-go-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin] # 需要打包的系统
        goarch: ["386",amd64,arm64] # 需要打包的架构
        exclude: # 排除某些平台和架构
          - goarch: arm64
            goos: windows
          - goarch: "386"
            goos: darwin
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # 一个默认的变量，用来实现往 Release 中添加文件
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.18 # 可以指定编译使用的 Golang 版本
          binary_name: "CVE-2023-42442" # 可以指定二进制文件的名称
          extra_files: README.md # 需要包含的额外文件
          sha256sum: TRUE
          pre_command: go mod init CVE-2023-42442
          # build_command: 
          ldflags: -s -w
